### ISSUE TITLE
ZeroDivisionError when there are no partitions of disk

### ISSUE THREAD

**Issue by Atoms** [fboender/ansible-cmdb#2] opened 2015-08-10 16:06 UTC
I'm trying to add in cmdb overview Citrix xenserver, Citrix xenserver by default has mounted iso 

/opt/xensource/packages/iso/XenCenter.iso
                       56M   56M     0 100% /var/xen/xc-install

in ansible facts gathered it shows under ansible_mounts as 

            {
                "device": "/opt/xensource/packages/iso/XenCenter.iso",.
                "fstype": "iso9660",.
                "mount": "/var/xen/xc-install",.
                "options": "ro,loop=/dev/loop0",.
                "size_available": 0,.
                "size_total": 53665792,.
                "uuid": "NA"
            },.
It's not the only one mount point which has size_available 0.

# ansible-cmdb  out/ > cmdb/overview.html
Traceback (most recent call last):
  File "/usr/local/bin/ansible-cmdb", line 134, in <module>
    sys.stdout.write(mytemplate.render(hosts=ansible.hosts))
  File "/usr/lib/python2.7/site-packages/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 783, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 815, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 841, in _exec_template
    callable_(context, *args, **kwargs)
  File "_usr_local_lib_ansible_cmdb_html_fancy_tpl", line 184, in render_body
  File "_usr_local_lib_ansible_cmdb_html_fancy_tpl", line 36, in col_disk_usage
  File "_usr_local_lib_ansible_cmdb_html_fancy_tpl", line 607, in render_col_disk_usage
ZeroDivisionError: float division by zero

**Comment by fboender** [comment] 2015-08-10 16:30
Hey Atoms,

Thanks for you bug report!

I can't seem to reproduce this problem. A size_available of 0 shouldn't be a problem with the latest version (v1.1 or master branch from Github), since the col_disk_usage is calculated as: (size_total - size_available) / size_total. I have several squashfs filesystems that have 0 available size.

Could you send me your entire out directory (ferry.boender@gmail.com) or a reduced/redacted minimal sample that reproduces the error?

**Comment by Atoms** [comment] 2015-08-10 17:12
ok, dig a little deeper, and yes, i was wrong :) 

            {
                "device": "//x.x.x.x/isolib",
                "fstype": "cifs",
                "mount": "/var/run/sr-mount/6d6a0ce1-d0e7-54e1-d6ab-0549cc582508",
                "options": "rw,mand",
                "size_available": 0,
                "size_total": 0,
                "uuid": "NA"
            },

when i remove this from ansible_mounts then all goes well, i cannot see it in df output, so i think or this library is dead or just disconnected and left in xencenter.... 

so i think you need to check if size_total is not 0

**Comment by fboender** [comment] 2015-08-11 05:55
The template was showing Disk Usage bars for disks smaller than 1MB, but they're supposed to be skipped just like the Disk Free and Disk Available columns. I've modified the template, and now the problem has gone away.

Thank you for your bugreport and help in reproducing the error. The master branch on github now includes a fix. I've released v1.2. You can download packages for v1.2 from  https://github.com/fboender/ansible-cmdb/releases/tag/1.2

I'm closing this bug.

**Closed by fboender** 2015-08-11 05:55 UTC
