### ISSUE TITLE
Issues running on Centos 6

### ISSUE THREAD

**Issue by hkdanalyser** [fboender/ansible-cmdb#109] opened 2017-02-24 21:10 UTC
Hey there,

I directly downloaded the rpm files for versions 1.20 and 1.19. Both times I am getting a very similar error. Is there a dependency that I am missing on my systems ?

I see the same error just calling the script without any parameters.

| => ansible-cmdb
Traceback (most recent call last):
  File "/usr/bin/ansible-cmdb", line 53, in <module>
    parser = optparse.OptionParser(version="%prog v{}".format(version))
ValueError: zero length field name in format

**Comment by fboender** [comment] 2017-02-25 10:29
Hi!

Which exact version of Centos do you have? It works for me on Centos 6.7. And which version of Python do you have?

**Comment by fboender** [comment] 2017-02-25 10:32
Never mind, it's not working for me either on Centos 6.7. I'll have a fix out for this as soon as possible.

**Comment by fboender** [comment] 2017-02-25 11:03
The problem is with Python v2.6, which is what CentOS 6 has. I thought I tested against CentOS v6, but I was mistaken. I've fixed the problems and released a new version of ansible-cmdb (v1.21). Hopefully this works for you!

Thank you very much for the bug report. I've accidentally totally overlooked testing against Python v2.6 for way too long.

I'm closing this issue. If you have further problems, please reopen it and we can have a further look.

**Closed by fboender** 2017-02-25 11:03 UTC

**Comment by hkdanalyser** [comment] 2017-02-27 17:21
Hey there,

Sorry about the delayed response. I was out of town this weekend. The new release has fixed the issue. Thank you so much for this really awesome tool !!!

**Comment by fboender** [comment] 2017-02-28 12:27
No worries. Thanks for testing and for the bug report!
