### ISSUE TITLE
ImportError: No module named ansiblecmdb

### ISSUE THREAD

**Issue by ShalbafZadeh** [fboender/ansible-cmdb#177] opened 2018-09-05 16:10 UTC
in a fresh installation of ansible-cmdb (1.28) via pip , you get this error on all ansible-cmdb commands 
```
[reza:~]$ ansible-cmdb 
Traceback (most recent call last):
  File "/usr/local/bin/../lib/ansiblecmdb/ansible-cmdb.py", line 19, in <module>
    import ansiblecmdb
ImportError: No module named ansiblecmdb
[reza:~]$ ansible-cmdb --debug
Traceback (most recent call last):
  File "/usr/local/bin/../lib/ansiblecmdb/ansible-cmdb.py", line 19, in <module>
    import ansiblecmdb
ImportError: No module named ansiblecmdb
[reza:~]$ 
```

**Comment by fboender** [comment] 2018-09-06 06:03
Duplicate of #178. I'm closing this one.

**Closed by fboender** 2018-09-06 06:03 UTC

**Comment by ghost** [comment] 2022-09-27 17:27
May i know how did you resolve this issue. am also facing same issue. please suggest me..
[root@iZ8ps62fkromnzmgr07pmnZ ansible-cmdb-1.30]# ansible-cmdb --version
Traceback (most recent call last):
  File "/usr/local/bin/../lib/ansiblecmdb/ansible-cmdb.py", line 19, in <module>
    from mako import exceptions
ImportError: No module named mako
[root@iZ8ps62fkromnzmgr07pmnZ ansible-cmdb-1.30]# sudo pip install ansible-cmdb
Requirement already satisfied (use --upgrade to upgrade): ansible-cmdb in /usr/lib/python2.7/site-packages
Collecting mako (from ansible-cmdb)
  Downloading http://ap-southeast-3.mirrors.cloud.aliyuncs.com/pypi/packages/b9/38/c25f0874ea71802fc6f1e9f0f88a7e9666818121b28991bbc1d8eddbcdb1/Mako-1.2.3.tar.gz (491kB)
    100% |################################| 491kB 69.0MB/s
  Running setup.py (path:/tmp/pip-build-u7VkcP/mako/setup.py) egg_info for package mako produced metadata for project name unknown. Fix your #egg=mako fragments.
  Requirement already satisfied (use --upgrade to upgrade): unknown from http://ap-southeast-3.mirrors.cloud.aliyuncs.com/pypi/packages/b9/38/c25f0874ea71802fc6f1e9f0f88a7e9666818121b28991bbc1d8eddbcdb1/Mako-1.2.3.tar.gz#sha256=7fde96466fcfeedb0eed94f187f20b23d85e4cb41444be0e542e2c8c65c396cd in /usr/lib/python2.7/site-packages (from ansible-cmdb)
Requirement already satisfied (use --upgrade to upgrade): jsonxs in /usr/lib/python2.7/site-packages (from ansible-cmdb)
Requirement already satisfied (use --upgrade to upgrade): ushlex in /usr/lib/python2.7/site-packages (from ansible-cmdb)
Requirement already satisfied (use --upgrade to upgrade): pyyaml in /usr/lib64/python2.7/site-packages (from ansible-cmdb)
You are using pip version 8.1.2, however version 22.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
