### ISSUE TITLE
name 'tokenize' is not defined

### ISSUE THREAD

**Issue by archf** [fboender/ansible-cmdb#98] opened 2017-01-31 19:58 UTC
Hi,
This projects looks awesome!  However I just did a first run after a fresh pip install:

```
sudo pip3 install ansible-cmdb
```

And after the fact generation with: ```ansible -i hosts all -m setup --tree  facts/myhosts/src``` 
````
ansible-cmdb -d  facts/myhosts/src > facts/myhosts/html            
data_dir = /usr/local/lib/ansiblecmdb/data
tpl_dir = /usr/local/lib/ansiblecmdb/data/tpl
static_dir = /usr/local/lib/ansiblecmdb/data/static
config_file = /home/archf/grepos/gpb/ansible.cfg
inventory hostfile = None
Parsing fact dir: facts/myhosts/src
[...snip...]
Reading host facts from facts/myhost/src/myhost
[...snip...]

template file = /usr/local/lib/ansiblecmdb/data/tpl/html_fancy.tpl
Template params: {'data_dir': '/usr/local/lib/ansiblecmdb/data', 'columns': None, 'lib_dir': '/usr/local/lib/ansiblecmdb/data', 'log': <logging.RootLogger object at 0x7f74ab1d38d0>, 'version': '1.19'}
Whoops, it looks like something went wrong while rendering the template.

The reported error was: NameError: name 'tokenize' is not defined

The full error was:
    
    Traceback (most recent call last):
      File "/usr/local/bin/ansible-cmdb", line 137, in <module>
        out = mytemplate.render(hosts=ansible.hosts, **params)
      File "/usr/lib/python3/dist-packages/mako/template.py", line 445, in render
        return runtime._render(self, self.callable_, args, data)
      File "/usr/lib/python3/dist-packages/mako/runtime.py", line 829, in _render
        **_kwargs_for_callable(callable_, data))
      File "/usr/lib/python3/dist-packages/mako/runtime.py", line 864, in _render_context
        _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
      File "/usr/lib/python3/dist-packages/mako/runtime.py", line 890, in _exec_template
        callable_(context, *args, **kwargs)
      File "/usr/local/lib/ansiblecmdb/data/tpl/html_fancy.tpl", line 1, in render_body
        <%
      File "/usr/local/lib/python3.5/dist-packages/jsonxs/__init__.py", line 2, in <module>
        del tokenize
    NameError: name 'tokenize' is not defined
    
The output is probably not correct.
```

**Comment by fboender** [comment] 2017-02-01 12:05
Confirmed. I'll try to get a fix out for this soon. The problem is in the jsonxs package, which I maintain.

**Comment by fboender** [comment] 2017-02-02 08:08
Hey Felix!

I've fixed the bug in jsonxs and uploaded a new package to the Python Package index. If you remove the jsonxs package from your virtualenv and reinstall, it should work now.

Thank you for your bug report. I'm closing this issue in the hope that it has been resolved. If not, please reopen it and we'll have a further look!

**Closed by fboender** 2017-02-02 08:08 UTC
Labels: bug

**Comment by archf** [comment] 2017-02-02 16:01
Thanks a lot! Works like a charm!
