### ISSUE TITLE
Error when reading dynamic inventory

### ISSUE THREAD

**Issue by dcj** [fboender/ansible-cmdb#69] opened 2016-04-12 23:05 UTC
I have a pretty large dynamic inventory file in JSON that contains lots of groups and variables.

When I added that to ansible-cmdb via the -i option, I get the following error:

```
Reading host facts from out/u40.r2.dc.drivescale.com
Traceback (most recent call last):
  File "/usr/local/bin/ansible-cmdb", line 96, in <module>
    ansible = ansiblecmdb.Ansible(args, options.inventory, options.fact_cache, debug=options.debug)
  File "/usr/local/lib/ansible-cmdb/ansiblecmdb/ansible.py", line 39, in __init__
    self._handle_inventory(self.inventory_path)
  File "/usr/local/lib/ansible-cmdb/ansiblecmdb/ansible.py", line 62, in _handle_inventory
    self._handle_inventory(os.path.join(inventory_path, fname))
  File "/usr/local/lib/ansible-cmdb/ansiblecmdb/ansible.py", line 55, in _handle_inventory
    self._parse_dyn_inventory(inventory_path)
  File "/usr/local/lib/ansible-cmdb/ansiblecmdb/ansible.py", line 168, in _parse_dyn_inventory
    dyninv_parser = parser.DynInvParser(stdout.decode('utf8'))
  File "/usr/local/lib/ansible-cmdb/ansiblecmdb/parser.py", line 381, in __init__
    self._parse_group(k, v)
  File "/usr/local/lib/ansible-cmdb/ansiblecmdb/parser.py", line 404, in _parse_group
    self._get_host(hostname)['hostvars'][var_key] = var_val
UnboundLocalError: local variable 'hostname' referenced before assignment
```

I will email you the file it was processing when this occurred.

It is entirely possible that the way I generate my dynamic inventory is causing this problem, although Ansible has been happily using it for months.

**Comment by fboender** [comment] 2016-04-13 05:59
Hi Don,

This looks like a bug in ansible-cmdb. If ansible can work with it, so should ansible-cmdb. :-)

The problem seems to be in the output of the dynamic inventory script.  Ansible-cmdb incorrectly informed you that it was last parsing "out/u40.r2.dc.drivescale.com", but that file wasn't the problem. I've added an extra message indicating the last thing it was parsing was the output of the dynamic inventory script.

Could you send me the output of the inventory script so that I can see what the problem is?

Thanks!

**Comment by fboender** [comment] 2016-04-18 15:35
Hey Don,

Sorry for the long delay! I've pushed a fix to the master branch that, at the very least, fixes the bug you encountered. I have to admit that at the moment, dynamic inventory scanning is a bit lacking. If you encounter any other problems or would like to see improvements, please let me know!

With kind regards,

Ferry

**Closed by fboender** 2016-04-18 15:35 UTC
