### ISSUE TITLE
inventory files with groups of groups causes an error

### ISSUE THREAD

**Issue by palmerit** [fboender/ansible-cmdb#16] opened 2015-08-19 19:58 UTC
If you have groups of groups, it will throw an error.

```
[haproxy:children]
lb

[lb:children]
lb-prod
lb-dev

[lb-prod]
lb1-prod
lb2-prod

[lb-dev]
lb1-dev
lb2-dev
```
when running ansible-cmdb with the -i flag,   it will error on the haproxy:children section, with:

$ ansible-cmdb -i hosts/default out/ > output.html
Traceback (most recent call last):
  File "/usr/bin/ansible-cmdb", line 290, in <module>
    ansible = Ansible(args, options.inventory)
  File "/usr/bin/ansible-cmdb", line 29, in __init__
    self.parse_hosts(self.hosts_file)
  File "/usr/bin/ansible-cmdb", line 110, in parse_hosts
    for hostname in normal_groups[apply_group_name]:
KeyError: 'lb'

**Comment by fboender** [comment] 2015-08-19 21:26
Hey Jeff! 

Thanks for the bug report!

Groups of groups are supported in the latest version of the Git repo. There is no package with that fix yet. Your use-case will probably still fail though, since I did not anticipate that a group "lb:children" would also count as a group called "lb". I will fix this as soon as possible.

**Comment by coryrwagner** [comment] 2015-08-19 22:35
I'm also seeing KeyError errors when trying to parse groups of groups.

**Comment by palmerit** [comment] 2015-08-20 00:03
Ferry,

Thanks for the fast reply.

I'm using the version from master,  and the groups of groups work as
advertised,  however it was the particular use-case I mentioned that was
failing.   I should have clarified in the issue report that the bug was
being filed against master, and not the 0.3.deb version.

Thanks!



On Wed, Aug 19, 2015 at 5:26 PM, Ferry Boender <notifications@github.com>
wrote:

> Hey Jeff!
>
> Thanks for the bug report!
>
> Groups of groups are supported in the latest version of the Git repo.
> There is no package with that fix yet. Your use-case will probably still
> fail though, since I did not anticipate that a group "lb:children" would
> also count as a group called "lb". I will fix this as soon as possible.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fboender/ansible-cmdb/issues/16#issuecomment-132791192>
> .
>



-- 
Jeff Palmer
https://PalmerIT.net

**Comment by coryrwagner** [comment] 2015-08-21 17:06
I'm still seeing KeyError errors when trying to parse groups of groups, with the latest trunk code from the repo.

Example:
```
[sftp-all:children]
sftp-product1
sftp-product2

[sftp-product1:children]
host1
host3

[sftp-product1:children]
hosta
hostd
```
It will complain about sftp-product1.

**Comment by fboender** [comment] 2015-08-21 20:15
Hey Cory!

Yes, I'm aware of this problem! The problem is with the fact that "sftp-product1:children" is itself also a group called "sftp-product1". I did not anticipate this. It means that children groups are basically recursive and I have to do a rewrite of the way I'm handling children groups. I'm planning on fixing this tomorrow.

**Comment by fboender** [comment] 2015-08-23 09:46
Hi Jeff!

I've rewritten the inventory parsing logic and committed it. (It took a bit to find a clean way of doing it). Could you check to see if it's handling your inventory properly now?

Thanks!

**Comment by coryrwagner** [comment] 2015-08-24 17:32
I can confirm that this change fixed the issues that I was having with nested groups.

**Comment by fboender** [comment] 2015-08-24 18:14
That's great to hear Cory! Thank you for verifying the fix. I'm going to release a new version with packages soon, as this is a rather important bugfix.

**Closed by fboender** 2015-08-24 18:14 UTC
Labels: bug

**Comment by palmerit** [comment] 2015-08-24 18:23
Ferry,


I was just able to confirm it works properly on my unmodified inventory directory too.
