### ISSUE TITLE
Host overview render fails

### ISSUE THREAD

**Issue by NikitaGl** [fboender/ansible-cmdb#119] opened 2017-06-15 08:50 UTC
Hello again!
It took me a while to get back to play with your app and I've encountered with a new problem.
Each time I try to generate a host overview it fails with such an error:

ansible-cmdb -d -p skip_empty=1 -f ./ansible-cmdb-facts/ > ./ansible-cmdb-html/index.html

> Whoops, it looks like something went wrong while rendering the template.

> The reported error was: UnicodeEncodeError: 'ascii' codec can't encode character u'\u0441' in position 0: ordinal not in range(128)
> 
> The full error was:

    Traceback (most recent call last):
      File "/usr/bin/ansible-cmdb", line 157, in <module>
        output = renderer.render(ansible.hosts, params)
      File "/usr/local/lib/ansible-cmdb/ansiblecmdb/render.py", line 45, in render
        return self._render_mako(hosts, vars)
      File "/usr/local/lib/ansible-cmdb/ansiblecmdb/render.py", line 62, in _render_mako
        return template.render(hosts=hosts, **vars)
      File "/usr/local/lib/ansible-cmdb/mako/template.py", line 443, in render
        return runtime._render(self, self.callable_, args, data)
      File "/usr/local/lib/ansible-cmdb/mako/runtime.py", line 803, in _render
        **_kwargs_for_callable(callable_, data))
      File "/usr/local/lib/ansible-cmdb/mako/runtime.py", line 835, in _render_context
        _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
      File "/usr/local/lib/ansible-cmdb/mako/runtime.py", line 860, in _exec_template
        callable_(context, *args, **kwargs)
      File "/usr/local/lib/ansible-cmdb/ansiblecmdb/data/tpl/html_fancy.tpl", line 32, in render_body
        <% html_host_overview(cols, hosts, skip_empty=skip_empty, link_type=link_type) %>
      File "/usr/local/lib/ansible-cmdb/ansiblecmdb/data/tpl/html_fancy_defs.html", line 247, in render_html_host_overview
        <%
    UnicodeEncodeError: 'ascii' codec can't encode character u'\u0441' in position 0: ordinal not in range(128)

> The output is probably not correct.

It probably might be something in ansible hosts file, but I'm not sure as it runs normally in playbooks and others. Do you have any thoughts?

**Comment by fboender** [comment] 2017-06-15 09:05
Are you running the latest version of the master branch? I recently fixed a problem with unicode in the templates, which it looks like this problem is related to.

Also, which Python version are you using? Python v2.x I assume, judging by the error?

**Comment by NikitaGl** [comment] 2017-06-15 09:23
[glushak@ansible ansible]$ ansible-cmdb --version
ansible-cmdb vMASTER
[glushak@ansible ansible]$ python --version
Python 2.7.5

Yup, it's the latest version, i've deleted the old one I've installed via pip and installed this manually.

P.S. Oh, by the way, I've noticed such line in output during make install:
gzip -9 -c contrib/ansible-cmdb.man.1 > /usr/local/man/man1/ansible-cmdb.man.1.gz
On my RHEL 7.3, to make man working, I moved it manually to /usr/share/man/man1/ansible-cmdb.1.gz.
However, it might be only my problem.

**Comment by fboender** [comment] 2017-06-15 14:49
Okay. You can probably use one of the official release until I fix the Unicode prpblem. Those should work. 

Thanks for the heads up about the man page. Its probably broken now. I never really tested that on redhat come to think of it. ;-)

Thanks for the info!

**Comment by NikitaGl** [comment] 2017-06-23 09:13
Hi again. Finally I got time to play with cmdb again and I've discovered that turning back to pip version is not working, I'm still recieving ascii codec error, so this problem is probably on my side. Could you explain, please, what arguments from main ansible is used to generate html page? It seems, like the problem is somewhere there.

**Comment by fboender** [comment] 2017-06-24 06:34
Ansible-cmdb generally uses Ansible's `hosts`file and the output of Ansible's fact gathering. The facts are stored in the `out` directory when you run the following command:

    mkdir out
    ansible -m setup --tree out/ all

I suspect that the `hosts` file or in one of the files in the `out` directory contains some unicode characters (like é or ç or something) that Ansible-cmdb doesn't like. Figuring out where exactly the problem is is kinda painful. You can try calling ansible-cmdb without the `-i hosts` argument or by temporary moving the `hosts` file to another location. If it still doesn't generate, then the problem is in the `out/` dir. I usually just delete files from the `out` dir until it works to narrow down which host is causing the problems.

If you want to, you can send a zip file with the `hosts` and `out/` files to my email address (ferry.boender@gmail.com), and I could have a look for you. The data you send me would be treated highly confidential and will be securely wiped once the problem is fixed.

**Comment by fboender** [comment] 2017-06-24 06:45
The problem might also be in the `host_vars` dir if you have one, since it is automatically included.

**Comment by NikitaGl** [comment] 2017-06-27 11:05
Small update: getting rid of current hosts file did the trick. The problem is that it's content was managed by the other admin, ho is on vacation, so I just did a backup and rewrote the file. Reviewing it by myself will be a pain in the ass, because: 
[glushak@ansible ansible]$ wc -l hosts-back
3078 hosts-back
Now I finally got back to my custom template error resolving C:

**Comment by fboender** [comment] 2017-07-08 08:11
Great work on figuring out where the problem was! I've managed to reproduce it now. I did not expect cyrillic host names :-D I'm still considering this a bug, so I'm going to keep the bug report open for now.

**Comment by fboender** [comment] 2017-07-08 08:28
I've pushed a commit to the master branch that fixes this problem. It was actually a side effect of the debug / logging facility.

Thanks a lot for figuring out the cause of this!

I'm closing this bug report.

**Closed by fboender** 2017-07-08 08:28 UTC
Labels: bug
