### ISSUE TITLE
AttributeError: 'list' object has no attribute 'items'

### ISSUE THREAD

**Issue by alexbarton** [fboender/ansible-cmdb#48] opened 2015-12-31 10:44 UTC
Running `ansible-cmdb reports/ >report.html` results in the following error here:
```
$ ansible all_managed -m setup --tree reports/ >/dev/null
$ ansible-cmdb reports/ >report.html
Traceback (most recent call last):
  File "/usr/local/bin/ansible-cmdb", line 632, in <module>
    sys.stdout.write(mytemplate.render(hosts=ansible.hosts, **params))
  File "/usr/local/Cellar/ansible-cmdb/1.6/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/local/Cellar/ansible-cmdb/1.6/mako/runtime.py", line 803, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/local/Cellar/ansible-cmdb/1.6/mako/runtime.py", line 835, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/local/Cellar/ansible-cmdb/1.6/mako/runtime.py", line 860, in _exec_template
    callable_(context, *args, **kwargs)
  File "_usr_local_Cellar_ansible_cmdb_1_6_html_fancy_tpl", line 277, in render_body
  File "_usr_local_Cellar_ansible_cmdb_1_6_html_fancy_tpl", line 30, in r_dict
  File "_usr_local_Cellar_ansible_cmdb_1_6_html_fancy_tpl", line 526, in render_r_dict
AttributeError: 'list' object has no attribute 'items'
make: *** [report.html] Error 1
```

How can I help to debug this?

**Comment by fboender** [comment] 2015-12-31 16:27
Hey Alexander,

Thanks for reporting the bug. It looks like there's something unexpected in one of the hosts files. 

I've put a template containing debugging information at http://www.electricmonk.nl/temp/html_fancy.tpl

If you could download it and then try with that template:

    $ ./ansible-cmdb -t /home/fboender/Downloads/html_fancy.tpl ../example/out > out.dump

It should give us an indication in which host and section the problem is occuring. It will be the last host and the last line of the output. If you could send me the offending hosts file (ferry.boender@gmail.com; anything you send me will be kept strictly confidential), or paste the last line in the output here, I can see if I can fix it. It would also be helpful to know which type of host (OS, mostly) the host giving the problem is.

Thanks for your help!

**Comment by fboender** [comment] 2015-12-31 16:27
Oops, accidentally closed the issue. Reopening.

**Comment by alexbarton** [comment] 2016-01-04 11:16
Specifying a full path name to a template file fails here:
```
ansible-cmdb -t ./html_fancy.tpl reports >out.txt
Template not found: /usr/local/Cellar/ansible-cmdb/1.6/./html_fancy.tpl.tpl
```

But I installed your "debug template" as "debug.tpl" as `/usr/local/Cellar/ansible-cmdb/1.6/debug.tpl` and called `ansible-cmdb` like this:
```
$ ansible-cmdb -t debug ./reports/ >out.txt
Traceback (most recent call last):
  File "/usr/local/bin/ansible-cmdb", line 632, in <module>
    sys.stdout.write(mytemplate.render(hosts=ansible.hosts, **params))
  File "/usr/local/Cellar/ansible-cmdb/1.6/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/local/Cellar/ansible-cmdb/1.6/mako/runtime.py", line 803, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/local/Cellar/ansible-cmdb/1.6/mako/runtime.py", line 835, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/local/Cellar/ansible-cmdb/1.6/mako/runtime.py", line 860, in _exec_template
    callable_(context, *args, **kwargs)
  File "_usr_local_Cellar_ansible_cmdb_1_6_debug_tpl", line 110, in render_body
TypeError: argument of type 'Undefined' is not iterable
```

`out.txt` doesn't contain anything after this, it is 0 bytes long, there is no output to `stdout` at all …

**Comment by alexbarton** [comment] 2016-01-04 11:25
Okay, but I found out by hand which inventory files do cause the problem: this are all host files of **OpenBSD** systems!

If I remove all OpenBSD systems from my `reports/` folder, `ansible-cmdb` works as expected.
But if I add an inventory file of an arbitrary OpenBSD system, it fails with the backtrace shown above.

**Comment by alexbarton** [comment] 2016-01-04 11:36
@fboender I sent you an example inventory file by email. Please let me know if I can test something or you need more information!

**Comment by fboender** [comment] 2016-01-04 11:59
Hey Alexander.

Thanks for figuring that out! I'll write up a fix soon.

**Comment by fboender** [comment] 2016-01-04 22:09
Hey Alexander,

I pushed a fix for OpenBSD facts to the master branch. There's still some missing information (see issue #51 ), but at least it doesn't crash now. Can you verify that it works?

Thanks in advance!

**Comment by fboender** [comment] 2016-01-07 10:18
I'm closing this issue in the assumption that things are working correctly now. If not, please reopen!

**Closed by fboender** 2016-01-07 10:18 UTC

**Comment by alexbarton** [comment] 2016-01-11 13:04
Thanks @fboender, I can confirm that your patches fixed the issue.
