### ISSUE TITLE
Mem Usage n/a

### ISSUE THREAD

**Issue by negativerad** [fboender/ansible-cmdb#74] opened 2016-05-06 19:30 UTC
The Mem Usage column shows n/a for all servers in the host overview. Yet inside the detailed information for each host under hardware section the memory information is populated correctly.

**Comment by fboender** [comment] 2016-05-10 17:45
Hey negativerad!

Thanks for the bug report. Could you send me the facts file for one of the hosts that doesn't display the memory properly? You can send it to my email address (ferry.boender@gmail.com). I will keep the information strictly confidential.

Thanks!

**Comment by fboender** [comment] 2016-06-03 09:40
Hey negativerad,

I haven't received any facts files from you yet. Without that information, it's impossible to see what the problem is you are experiencing.

Regards,

Ferry

**Comment by fboender** [comment] 2016-06-08 19:32
Hey negativerad,

I've closed this bug report because without further feedback I won't be able to reproduce this issue. If you have the time and can send me some fact files, feel free to reopen this issue!

Thanks!

**Closed** 2016-06-08 19:31 UTC
Labels: bug
